# Generated by Django 5.0.7 on 2026-09-11 20:38

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, max_length=90, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='assunto')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('is_read', models.BooleanField(default=False, verbose_name='lida')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
            ],
            options={
                'verbose_name': 'Mensagem de Contacto',
                'verbose_name_plural': 'Mensagens de Contacto',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.CharField(max_length=200, verbose_name='instituição')),
                ('degree', models.CharField(max_length=200, verbose_name='grau/curso')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='local')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Formação Académica',
                'verbose_name_plural': 'Formação Académica',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='título/cargo')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='organização/cliente')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='local')),
                ('experience_type', models.CharField(choices=[('work', 'Experiência Profissional'), ('project', 'Projeto Autónomo'), ('certification', 'Certificação')], default='work', max_length=20, verbose_name='tipo')),
                ('start_date', models.DateField(verbose_name='início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fim')),
                ('is_current', models.BooleanField(default=False, verbose_name='atual')),
                ('description', models.TextField(verbose_name='descrição')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Linha do Tempo (Experiência)',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Tiago Vítor Banze', max_length=150)),
                ('headline', models.CharField(default='Engenheiro Informático & Desenvolvedor Full-Stack', max_length=200)),
                ('bio_short', models.TextField(default='Engenheiro Informático formado pela Universidade Metodista Unida de Moçambique, com raciocínio analítico apurado e paixão por transformar ideias em sistemas funcionais — do software ao hardware.')),
                ('bio_long', models.TextField(blank=True)),
                ('location', models.CharField(default='Maxixe, Inhambane, Moçambique', max_length=150)),
                ('email', models.EmailField(blank=True, default='contacto@tiagobanze.dev', max_length=254)),
                ('whatsapp_number', models.CharField(default='+258847388489', max_length=20)),
                ('github_url', models.URLField(default='https://github.com/tiago-banze')),
                ('facebook_url', models.URLField(default='https://www.facebook.com/tiago.banze.1')),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_description', models.CharField(max_length=220, verbose_name='descrição curta')),
                ('description', models.TextField(verbose_name='descrição detalhada')),
                ('icon', models.CharField(choices=[('code', 'Código / Desenvolvimento'), ('graduation-cap', 'Académico'), ('monitor', 'Treinamento de Software'), ('cpu', 'Manutenção de Computadores'), ('zap', 'Eletrotécnica'), ('smartphone', 'Assistência Mobile')], default='code', max_length=30, verbose_name='ícone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='nome')),
                ('category', models.CharField(choices=[('backend', 'Back-End'), ('frontend', 'Front-End'), ('embedded', 'Eletrónica / Embarcados'), ('network', 'Redes & Infraestrutura'), ('tools', 'Ferramentas & Outras')], max_length=20, verbose_name='categoria')),
                ('proficiency', models.PositiveSmallIntegerField(default=70, verbose_name='proficiência (0-100)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('excerpt', models.CharField(max_length=280, verbose_name='resumo')),
                ('content', models.TextField(verbose_name='conteúdo (Markdown)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='imagem de capa')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado')], default='published', max_length=10, verbose_name='estado')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publicado em')),
                ('reading_time_minutes', models.PositiveIntegerField(default=5, verbose_name='tempo de leitura (min)')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='meta título')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='meta descrição')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='api.category')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Publicação do Blog',
                'verbose_name_plural': 'Publicações do Blog',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=170, unique=True)),
                ('summary', models.CharField(max_length=250, verbose_name='resumo')),
                ('problem', models.TextField(blank=True, verbose_name='problema técnico')),
                ('solution', models.TextField(blank=True, verbose_name='solução aplicada')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='imagem de capa')),
                ('repo_url', models.URLField(blank=True, verbose_name='repositório GitHub')),
                ('live_url', models.URLField(blank=True, verbose_name='demo ao vivo')),
                ('status', models.CharField(choices=[('production', 'Em Produção'), ('completed', 'Concluído'), ('in_progress', 'Em Desenvolvimento'), ('archived', 'Arquivado')], default='completed', max_length=20, verbose_name='estado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('tech_tags', taggit.managers.TaggableManager(blank=True, help_text='Ex.: Python, Django, React, IoT, C++', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tecnologias')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
    ]
