# Generated by Django 5.0.7 on 2026-09-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, default='tiagovbanze@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(default='Tiago Victor Banze', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='headline',
            field=models.CharField(default='Engenheiro Informático | Desenvolvedor Full-Stack | Técnico de Redes e Telecomunicações | Técnico Eletricista Residencial', max_length=200),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('content', models.TextField(max_length=1000, verbose_name='comentário')),
                ('is_approved', models.BooleanField(default=True, verbose_name='aprovado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.post')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-created_at'],
            },
        ),
    ]
