# Generated by Django 5.0.7 on 2026-09-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_profile_email_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200, verbose_name='título do curso/certificado')),
                ('issuer', models.CharField(max_length=200, verbose_name='instituição emissora')),
                ('issuer_url', models.URLField(blank=True, verbose_name='link da instituição (opcional)')),
                ('issue_date', models.DateField(verbose_name='data de emissão')),
                ('credential_url', models.URLField(blank=True, verbose_name='link do certificado/credencial (opcional)')),
                ('file', models.FileField(blank=True, help_text='Aceita imagem (jpg/png) ou PDF.', null=True, upload_to='certifications/', verbose_name='ficheiro do certificado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'Certificação',
                'verbose_name_plural': 'Certificações',
                'ordering': ['order', '-issue_date'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Imagem opcional mostrada por baixo do texto da secção "Sobre mim".', null=True, upload_to='profile/', verbose_name='imagem da secção Sobre mim'),
        ),
    ]
